### ISSUE TITLE
Phoenix url与驱动不兼容

### ISSUE THREAD

**Issue by lixz3321** [gaogao110/flink-sql-connector-phoenix#2]
PhoenixDialect类中的这部分代码，其中校验url的开头是不是有误呢，这样jdbc:phoenix开头的url不能校验通过，这种url对于phoenix-core依赖中的驱动似乎不兼容啊

 @Override
    public boolean canHandle(String url) {
        return url.startsWith("jdbc:org.apache.flink.connector.phoenix:");
    }

**Comment by gaogao110** [comment]
谢谢您的提醒，是的，之前在批量修改的时候，工具自动修改了，已经 pr fix了

**Comment by gaogao110** [comment]
谢谢您的提醒，是的，之前在批量修改的时候，工具自动修改了，已经 pr fix了
